# Generated by Django 5.0.1 on 2024-01-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Item',
            new_name='OrderItem',
        ),
    ]
